### ISSUE TITLE
Support of ACCDB format

### ISSUE THREAD

**Issue by kc-frei** [epam/SciGlass#2]
Dear SciGlass team, thanks for your effort for creating such a great database! Unfortunately due to the IT restriction at our institute, we can't install the older version of Access to open file in MDB format. Is it possible to have another release with ACCDB format? Thanks again!

**Comment by derekphilipau** [comment]
@kc-frei can you send me a copy of the old database from this project?  I would very much appreciate it, as it has been removed from the code here and I've not gotten a response from them.  I would also need to update it to a newer version of Access and would happily share the updated file with you.

**Comment by drcassar** [comment]
@kc-frei and @derekphilipau I've converted the SciGlass database to plain text; it is available in this fork: https://github.com/drcassar/SciGlass.

**Comment by derekphilipau** [comment]
@drcassar this is incredible, thank you for preserving this data.

**Comment by kc-frei** [comment]
@drcassar thanks a ton for your efforts! 
@derekphilipau sorry for the late reply, but I guess it's not needed anymore?
